#!/bin/bash
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo dir = $DIR
ip="$(ipconfig getifaddr en0)"
echo ip4 = $ip
PORT=$"8000"
echo port = $PORT
if which xdg-open > /dev/null
then
  xdg-open http://"${ip}:${PORT}"
elif which gnome-open > /dev/null
then
  gnome-open http://"${ip}:${PORT}"
else
 open http://"${ip}:${PORT}"
fi
python3 -m http.server -d "$DIR/dist" 8000

